name: Atualizar Steam

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Gerar steam.json
        run: |
          curl "https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=${{ secrets.STEAM_API_KEY }}&steamid=${{ secrets.STEAM_ID }}&include_appinfo=true&include_played_free_games=true" > data/steam.json

      - name: Gerar perfil.json
        run: |
          curl "https://api.steampowered.com/ISteamUser/GetPlayerSummaries/v2/?key=${{ secrets.STEAM_API_KEY }}&steamids=${{ secrets.STEAM_ID }}" > data/perfil.json

      - name: Gerar conquistas.json
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
        run: |
          node scripts/update-achievements.js

      - name: Gerar amigos.json
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
        run: |
          node scripts/update-friends.js

      - name: Gerar friend-games.json
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        run: |
          node scripts/update-friend-games.js

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/steam.json
          git add data/perfil.json
          git add data/conquistas.json
          git add data/amigos.json
          git add data/friend-games.json

          if ! git diff --staged --quiet; then
            git commit -m "Atualizacao Steam"
            git push
          fi
